- .vscode/settings.json
- kubernetes/postgres/applications/kustomization.yaml
- kubernetes/postgres/applications/stackrox/longhorn.yaml
- kubernetes/postgres/applications/stackrox/network-policy.yaml
- kubernetes/postgres/applications/stackrox/postgres.yaml
- kubernetes/postgres/applications/stackrox/pv.yaml
- kubernetes/stackrox-central/README.md
- kubernetes/stackrox-central/base/config-map.yaml
- kubernetes/stackrox-central/base/deployment.yaml
- kubernetes/stackrox-central/base/hpa.yaml
- kubernetes/stackrox-central/base/network-policy.yaml
- kubernetes/stackrox-central/base/pvc.yaml
- kubernetes/stackrox-central/base/rbac.yaml
- kubernetes/stackrox-central/base/secret.yaml
- kubernetes/stackrox-central/base/service.yaml
- kubernetes/stackrox-central/overlays/okd/route.yaml
- kubernetes/stackrox-central/overlays/okd/scc.yaml
- kubernetes/stackrox-secure/base/config-map.yaml
- kubernetes/stackrox-secure/base/daemon-set.yaml
- kubernetes/stackrox-secure/base/deployment.yaml
- kubernetes/stackrox-secure/base/network-policy.yaml
- kubernetes/stackrox-secure/base/rbac.yaml
- kubernetes/stackrox-secure/base/secret.yaml
- kubernetes/stackrox-secure/base/service.yaml
- kubernetes/stackrox-secure/base/webhook.yaml
- kubernetes/stackrox-secure/overlays/k3s/cluster-name.yaml
- kubernetes/stackrox-secure/overlays/okd/cluster-name.yaml
- kubernetes/stackrox-secure/overlays/okd/scc.yaml
- kubernetes/stackrox-secure/overlays/sandbox/cluster-name.yaml
- kubernetes/stackrox-secure/overlays/sandbox/scc.yaml
Upgrade to StackRox 4.0
Use an External PostgresDB
> StackRox 4.0 & External Postgres Migration

- .tekton/apache-php-image.yaml
- .tekton/toolbox-image.yaml
- .vscode/settings.json
- containers/apache-php/containerfile
- containers/toolbox/containerfile
- kubernetes/tekton/components/cluster-tasks/buildah.yaml
- tekton/base/kustomization.yaml
- tekton/base/repo.yaml
> PAC: Image Build Pipelines

- .tekton/ansible.yaml
- .tekton/apache-php-image.yaml
- .tekton/overlay-test.yaml
- .tekton/toolbox-image.yaml
- containers/apache-php/containerfile
- containers/toolbox/containerfile
- kubernetes/tekton/base/resource-quota.yaml
- kubernetes/tekton/components/cluster-tasks/kustomization.yaml
- kubernetes/tekton/components/gosmee/kustomization.yaml
- kubernetes/tekton/components/hub/hub.yaml
- kubernetes/tekton/components/hub/kustomization.yaml
- kubernetes/tekton/components/hub/postgres.yaml
- kubernetes/tekton/components/hub/secret.yaml
- kubernetes/tekton/overlays/operator/kustomization.yaml
- task/buildah/0.5.1/README.md
- task/buildah/0.5.1/buildah.yaml
- task/git-clone/0.9.1/README.md
- task/git-clone/0.9.1/git-clone.yaml
- task/github-set-status/0.4.1/README.md
- task/github-set-status/0.4.1/github-set-status.yaml
- task/k8s-deploy/0.1.1/README.md
- task/k8s-deploy/0.1.1/k8s-deploy.yaml
- Deploy TektonHub through Tekton Operator
- Migrate Cluster Tasks to TektonHub Git Structure
- Reference TektonHub Tasks in Pipelines as Cdoe
> Tekton Hub

- .tekton/terraform-apply.yaml
- .tekton/terraform-plan.yaml
- .tekton/terraform.yaml
- README.md
- containers/toolbox/containerfile
- tekton/base/ansible-task.yaml
- tekton/base/configmap.yaml
- tekton/base/kustomization.yaml
- tekton/base/terraform-task.yaml
- terraform/gcp/HomeLab/homelab/keep-alive.tf
- terraform/gcp/HomeLab/homelab/main.tf
- terraform/gcp/HomeLab/homelab/truenas.tf
Terraform/Tofu Pipeline Incept
> Terraform/Tofu Pipeline Incept

- .tekton/overlay-test.yaml
- .vscode/settings.json
- ansible/playbooks/desktop/kubernetes.yaml
- containers/toolbox/containerfile
- containers/udi/containerfile
- kubernetes/cockroachdb/base/webhook.yaml
- kubernetes/dragonfly-operator/base/crd.yaml
- kubernetes/network-observability/base/flow-collector.yaml
- main.bash
- task/buildah/0.5.1/buildah.yaml
- tekton/base/overlay-test.yaml
> KubeConform Incept

- .vscode/settings.json
- kubernetes/argocd/applications/imagepuller.yaml
- kubernetes/argocd/applications/kustomization.yaml
- kubernetes/eclipse-che/base/cheCluster.yaml
- kubernetes/imagepuller/base/imagepuller.yaml
- kubernetes/imagepuller/base/installplan-approver.yaml
- kubernetes/imagepuller/base/kustomization.yaml
- kubernetes/imagepuller/base/limit-range.yaml
- kubernetes/imagepuller/base/namespace.yaml
- kubernetes/imagepuller/base/operator-group.yaml
- kubernetes/imagepuller/base/resource-quota.yaml
- kubernetes/imagepuller/base/subscription.yaml
- kubernetes/imagepuller/overlays/okd/kustomization.yaml
Kubernetes Imagepuller Operator
> Kubernetes Imagepuller Operator

- kubernetes/argocd/applications/container-security-operator.yaml
- kubernetes/argocd/applications/kustomization.yaml
- kubernetes/container-security/README.md
- kubernetes/container-security/base/catalog-source.yaml
- kubernetes/container-security/base/installplan-approver.yaml
- kubernetes/container-security/base/kustomization.yaml
- kubernetes/container-security/base/limit-range.yaml
- kubernetes/container-security/base/namespace.yaml
- kubernetes/container-security/base/operator-group.yaml
- kubernetes/container-security/base/resource-quota.yaml
- kubernetes/container-security/base/subscription.yaml
- kubernetes/container-security/overlays/okd/kustomization.yaml
- kubernetes/tekton/base/config.yaml
- okd/okd-configuration/base/certificates/ingress-controller.yaml
> Container Security Operator

- kubernetes/dragonfly-operator/base/crd.yaml
- kubernetes/dragonfly-operator/base/deployment.yaml
- kubernetes/dragonfly-operator/base/kustomization.yaml
- kubernetes/dragonfly-operator/base/kyverno.yaml
- kubernetes/gitea/base/dragonfly/dragonfly.yaml
- kubernetes/quay/base/dragonfly/dragonfly.yaml
Use Kyverno to Patch out fsgroup from operator config.
> fix: Patch out fsgroup from Dragonfly

- kubernetes/ceph/base/ingress.yaml
- kubernetes/ceph/base/namespace.yaml
- kubernetes/cert-manager/README.md
- kubernetes/cert-manager/base/resource-quota.yaml
- kubernetes/cert-manager/components/cloudflare/cluster-issuer.yaml
- kubernetes/cert-manager/components/trust-manager/bundle.yaml
- kubernetes/cert-manager/components/trust-manager/certificate.yaml
- kubernetes/cert-manager/components/trust-manager/crd.yaml
- kubernetes/cert-manager/components/trust-manager/deployment.yaml
- kubernetes/cert-manager/components/trust-manager/issuer.yaml
- kubernetes/cert-manager/components/trust-manager/kustomization.yaml
- kubernetes/cert-manager/components/trust-manager/pdb..yaml
- kubernetes/cert-manager/components/trust-manager/rbac.yaml
- kubernetes/cert-manager/components/trust-manager/service-monitor.yaml
- kubernetes/cert-manager/components/trust-manager/webhook.yaml
- kubernetes/cert-manager/overlays/okd/kustomization.yaml
- kubernetes/cert-manager/trust-values.yaml
- kubernetes/gitea/base/namespace.yaml
- kubernetes/gitea/overlays/okd/route.yaml
- kubernetes/homeassistant/base/namespace.yaml
- kubernetes/homeassistant/overlays/okd/ingress.yaml
- kubernetes/homeassistant/overlays/okd/kustomization.yaml
- kubernetes/nextcloud/base/namespace.yaml
- kubernetes/nextcloud/overlays/okd/route.yaml
- kubernetes/vault/base/namespace.yaml
- kubernetes/vault/overlays/okd/route.yaml
- kubernetes/zitadel/base/namespace.yaml
- kubernetes/zitadel/base/route.yaml
Switch from Passthrough to Re-Encrypt to Preserve Source IP
> feat(Trust-Manager): Incept && Re-Encrypt All Passthrough Routes

- containers/apache-php/containerfile
- kubernetes/quay/base/postgres/clair/postgres.yaml
- kubernetes/quay/base/subscription.yaml
- tekton/base/push-secret.yaml
Switch to Using Short Lived Tokens for Internal Quay, and Image Build Test
> feat(Quay 3.13): Internal Quay, WIF Robot Accounts, Image Build

- .vscode/settings.json
- kubernetes/argocd/applications/blackbox-exporter.yaml
- kubernetes/argocd/applications/kustomization.yaml
- kubernetes/blackbox-exporter/base/deployment.yaml
- kubernetes/blackbox-exporter/base/kustomization.yaml
- kubernetes/blackbox-exporter/base/namespace.yaml
- kubernetes/blackbox-exporter/base/pdb.yaml
- kubernetes/blackbox-exporter/base/service.yaml
- kubernetes/blackbox-exporter/components/kustomization.yaml
- kubernetes/blackbox-exporter/components/probes.yaml
- kubernetes/blackbox-exporter/components/prometheus-rules.yaml
- kubernetes/blackbox-exporter/overlays/okd/kustomization.yaml
- kubernetes/influxdb/base/kustomization.yaml
- kubernetes/influxdb/base/probe.yaml
- kubernetes/influxdb/overlays/okd/route.yaml
- kubernetes/loki/base/route.yaml
> feat(BlackBox Exporter): Incept

- kubernetes/ceph/base/certificate.yaml
- kubernetes/cert-manager/components/cloud-dns/README.md
- kubernetes/cert-manager/components/cloud-dns/cluster-issuer.yaml
- kubernetes/cert-manager/components/cloud-dns/gcp-credentials-request.yaml
- kubernetes/cert-manager/components/cloud-dns/kustomization.yaml
- kubernetes/cert-manager/components/cloud-dns/kyverno.yaml
- kubernetes/cert-manager/overlays/okd/kustomization.yaml
- kubernetes/stackrox-central/base/certificate.yaml
- kubernetes/zitadel/base/certificate.yaml
- okd/okd-configuration/base/certificates/api-certificate.yaml
- terraform/homelab/cloud-dns.tf
- Add Cluster Wide Workload Identity based Google Credentials to Cert Manager
- Switch all ```okd.arthurvardevanyan.com``` domains to use this issuer
> feat(Cloud DNS): Cert Manager

- .vscode/settings.json
- kubernetes/argocd/applications/kustomization.yaml
- kubernetes/argocd/applications/netbox.yaml
- kubernetes/dragonfly-operator/base/network-policy.yaml
- kubernetes/netbox/README.md
- kubernetes/netbox/base/configmap.yaml
- kubernetes/netbox/base/cronjob.yaml
- kubernetes/netbox/base/deployment.yaml
- kubernetes/netbox/base/dragonfly/dragonfly.yaml
- kubernetes/netbox/base/dragonfly/network-policy.yaml
- kubernetes/netbox/base/dragonfly/pdb.yaml
- kubernetes/netbox/base/ingress.yaml
- kubernetes/netbox/base/kustomization.yaml
- kubernetes/netbox/base/limit-range.yaml
- kubernetes/netbox/base/namespace.yaml
- kubernetes/netbox/base/network-policy.yaml
- kubernetes/netbox/base/object-bucket-claim.yaml
- kubernetes/netbox/base/pdb.yaml
- kubernetes/netbox/base/postgres/network-policy.yaml
- kubernetes/netbox/base/postgres/postgres.yaml
- kubernetes/netbox/base/postgres/secret.yaml
- kubernetes/netbox/base/resource-quota.yaml
- kubernetes/netbox/base/secret.yaml
- kubernetes/netbox/base/service-account.yaml
- kubernetes/netbox/base/service.yaml
- kubernetes/netbox/base/velero.yaml
- kubernetes/netbox/overlays/okd/kustomization.yaml
- kubernetes/netbox/values.yaml
> feat(Netbox): Incept

- containers/toolbox/containerfile
- kubernetes/mariadb-galera/base/mysqldump/cronjob.yaml
- kubernetes/mariadb-galera/base/statefulset.yaml
- kubernetes/netbox/base/cronjob.yaml
- kubernetes/openshift-logging/base/object-bucket-claim.yaml
- kubernetes/phpmyadmin/base/deployment.yaml
- kubernetes/postgres/components/pg_dump/network-policy.yaml
- kubernetes/postgres/components/pg_dump/secret.yaml
- okd/okd-configuration/base/image-mirror-set.yaml
https://github.com/ArthurVardevanyan/Analytics-for-Spotify/commit/a776fa84c67022cc4795bfaf40f9ee1677577e88
> feat(Postgress): Switch App to PSQL

- kubernetes/ceph/overlays/sandbox/kustomization.yaml
- kubernetes/ceph/overlays/sandbox/nncp.yaml
- kubernetes/cert-manager/overlays/okd-sandbox/kustomization.yaml
- kubernetes/kubevirt/overlays/sandbox/kustomization.yaml
- kubernetes/nmstate/overlays/okd/network/sandbox/nad.yaml
- kubernetes/nmstate/overlays/okd/network/sandbox/nncp.yaml
- kubernetes/nmstate/overlays/sandbox/network/nad.yaml
- kubernetes/nmstate/overlays/sandbox/network/nncp.yaml
- okd/openshift-monitoring/base/openshift-monitoring-cr-controller/deployment.yaml
- okd/openshift-monitoring/overlays/sandbox/kustomization.yaml
- sandbox/kubevirt/okd/configs/agent-config.yaml
- sandbox/kubevirt/okd/vm/okd1.yml
- sandbox/kubevirt/okd/vm/okd2.yml
- sandbox/kubevirt/okd/vm/okd3.yml
- vms/overlays/sandbox/fedora.yaml
- Switch from OVS Bridge to Linux Bridge
- Additional Nested NADs were not functional.
- Switch From Trying to Use Trunked VLANs to Interface per VLAN
- Still Flacky
> feat(Sandbox): Switch from OVS Bridge to Linux Bridge

- kubernetes/nmstate/overlays/okd/network/sandbox/nad.yaml
- kubernetes/nmstate/overlays/okd/network/sandbox/nncp.yaml
> fix(Sandbox): OVS -> Linux Bridge

- kubernetes/prometheus/components/node-exporter/daemonset.yaml
- kubernetes/stackrox-central/README.md
- kubernetes/stackrox-central/base/config-map.yaml
- kubernetes/stackrox-central/base/crds.yaml
- kubernetes/stackrox-central/base/deployment.yaml
- kubernetes/stackrox-central/base/hpa.yaml
- kubernetes/stackrox-central/base/kustomization.yaml
- kubernetes/stackrox-central/base/network-policy.yaml
- kubernetes/stackrox-central/base/postgres/postgres.yaml
- kubernetes/stackrox-central/base/prometheusRule.yaml
- kubernetes/stackrox-central/base/rbac.yaml
- kubernetes/stackrox-central/base/service-monitor.yaml
- kubernetes/stackrox-central/base/service.yaml
- kubernetes/stackrox-central/overlays/okd/route.yaml
- kubernetes/stackrox-secure/base/daemon-set.yaml
- kubernetes/stackrox-secure/base/deployment.yaml
- kubernetes/stackrox-secure/base/network-policy.yaml
- kubernetes/stackrox-secure/base/rbac.yaml
- kubernetes/stackrox-secure/base/service.yaml
- kubernetes/stackrox-secure/base/webhook.yaml
- kubernetes/stackrox-secure/overlays/okd/prometheusRule.yaml
- kubernetes/stackrox-secure/overlays/okd/serviceMonitor.yaml
> chore(stackrox): update

- kubernetes/pihole/components/pihole-infra/statefulset.yaml
- kubernetes/pihole/components/pihole/statefulset.yaml
- kubernetes/pihole/components/vlan3/statefulset.yaml
TODO: Proper log rotation / ephemeral storage pvc
> fix(pihole): EmptyDir for Logs

- okd/openshift-monitoring/base/rules.yaml
> feat(network-traffic-alert): monitor nic usage

- kubernetes/argocd/applications/kustomization.yaml
- kubernetes/stackrox-central/base/config-map.yaml
- kubernetes/stackrox-central/base/crds.yaml
- kubernetes/stackrox-central/base/deployment.yaml
- kubernetes/stackrox-central/base/hpa.yaml
- kubernetes/stackrox-central/base/kustomization.yaml
- kubernetes/stackrox-central/base/network-policy.yaml
- kubernetes/stackrox-central/base/postgres/kustomization.yaml
- kubernetes/stackrox-central/base/prometheusRule.yaml
- kubernetes/stackrox-central/base/pvc.yaml
- kubernetes/stackrox-central/base/rbac.yaml
- kubernetes/stackrox-central/base/secret.yaml
- kubernetes/stackrox-central/base/service-monitor.yaml
- kubernetes/stackrox-central/base/service.yaml
- kubernetes/stackrox-secure/README.md
- kubernetes/stackrox-secure/base/config-map.yaml
- kubernetes/stackrox-secure/base/daemon-set.yaml
- kubernetes/stackrox-secure/base/deployment.yaml
- kubernetes/stackrox-secure/base/network-policy.yaml
- kubernetes/stackrox-secure/base/rbac.yaml
- kubernetes/stackrox-secure/base/service.yaml
- kubernetes/stackrox-secure/base/webhook.yaml
- kubernetes/stackrox-secure/overlays/okd/prometheusRule.yaml
- kubernetes/stackrox-secure/overlays/okd/serviceMonitor.yaml
> chore(Stackrox 4.8 Rebuild)

- okd/okd-configuration/components/image-mirror/image-mirror-set.yaml
- okd/okd-configuration/overlays/okd/kustomization.yaml
- okd/okd-configuration/overlays/sandbox/kustomization.yaml
NeverContactSource still seems broken, reenabling with everything on AllowContactingSource
> feat(image-mirror): re-enable without block

- .vscode/settings.json
- kubernetes/argocd/applications/kube-descheduler.yaml
- kubernetes/kube-descheduler/README.md
- kubernetes/kube-descheduler/base/descheduler.yaml
- kubernetes/kube-descheduler/base/installplan-approver.yaml
- kubernetes/kube-descheduler/base/kustomization.yaml
- kubernetes/kube-descheduler/base/namespace.yaml
- kubernetes/kube-descheduler/base/operator-group.yaml
- kubernetes/kube-descheduler/base/subscription.yaml
- kubernetes/kube-descheduler/overlays/okd/kustomization.yaml
3 Node Cluster has server imbalance post rolling reboot.
> feat(descheduler): incept

- kubernetes/nextcloud/base/deployment.yaml
- kubernetes/nextcloud/components/backup/cronjob.yaml
- kubernetes/nextcloud/components/backup/kustomization.yaml
- kubernetes/nextcloud/components/backup/network-policy.yaml
- kubernetes/nextcloud/components/backup/rbac.yaml
- kubernetes/nextcloud/components/backup/secret.yaml
- kubernetes/nextcloud/components/backup/unas.sh
- kubernetes/nextcloud/components/openshift/egress-firewall.yaml
- kubernetes/nextcloud/overlays/okd/kustomization.yaml
Dump User Data using Nextclouds frontend webdav to dedicated smb shares
> feat(nextcloud): front end backup
